### ISSUE TITLE
Issue when loading project into VS17

### ISSUE THREAD

**Issue by itcotta** [Alovchin91/WinRTDesktopInterop#3]
The "WinRtComponent" project failes to load when trying to open this on Visual Studio 2017:

![image](https://user-images.githubusercontent.com/13465457/43948146-4eed7696-9c8a-11e8-8655-e7b0a4b0a903.png)

```
Project 'WinRtComponent' could not be loaded because it's missing install components. To fix this launch Visual Studio setup with the following selections:
Microsoft.Windows.CppWinRT

C:\Users\me\Downloads\WinRTDesktopInterop-master\WinRtComponent\WinRtComponent.vcxproj : error  : Value cannot be null.
Parameter name: hierarchy
```

I've installed the "Windows 10 SDK build 17134"

![image](https://user-images.githubusercontent.com/13465457/43947982-cae2dc60-9c89-11e8-9e46-10fb58ae8c2f.png)

**Comment by Alovchin91** [comment]
Hi @itcotta,

You need to install Microsoft’s C++/WinRT compiler in order to load and build that project. To do that, open “Tools > Extensions and Updates” in Visual Studio, search online for “C++/WinRT” extension from Microsoft and install it. It might require you to install additional VS components.

You don’t need any other SDKs except 17134 for that.
